sudo: required

services:
  - docker
  
before_install:
  - docker build -t alecgullon/laravel -f ./docker/laravel/Dockerfile.dev ./docker/laravel
  
script:
  - docker run laravel ./vendor/bin/phpunit

after_install:
  - docker build -t alecgullon/laravel ./docker/laravel
  - docker build -t alecgullon/mysql ./docker/mysql
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push alecgullon/laravel
  - docker push alecgullon/mysql
